# dependabot.yml file to update yarn dependencies

version: 2
updates:
  # Enable version updates for npm
  # use "npm" for yarn, per https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#supported-repositories-and-ecosystems
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    # Add proper reviewers to the PR
    reviewers:
      - "ArtBlocks/eng-approvers-contracts"
