version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  lint-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install
          command: yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test

workflows:
  run-ci:
    jobs:
      - lint-and-test