version: 2.1

orbs:
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@3.0.0

jobs:
  lint-and-test:
    docker:
      - image: "cimg/base:stable"
    resource_class: medium
    steps:
      - checkout
      - node/install:
          install-yarn: true
          lts: true
      - node/install-packages:
          pkg-manager: yarn
      - run: node --version
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test

workflows:
  run-ci:
    jobs:
      - lint-and-test
