version: 2.1

orbs:
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@3.0.0

jobs:
  checkout_and_compile:
    docker:
      - image: "cimg/base:stable"
    resource_class: large
    working_directory: ~/artblocks-contracts
    steps:
      - checkout
      - node/install:
          install-yarn: true
          lts: true
      - node/install-packages:
          pkg-manager: yarn
      - run: node --version
  lint:
    docker:
      - image: "cimg/base:stable"
    resource_class: large
    steps:
      - node/install:
          install-yarn: true
          lts: true
      - run:
          name: Lint
          command: yarn lint
  test:
    docker:
      - image: "cimg/base:stable"
    resource_class: large
    working_directory: ~/artblocks-contracts
    parallelism: 5
    steps:
      - node/install:
          install-yarn: true
          lts: true
      - run:
          name: Hardhat Test
          command: |
            TEST_FILES="$(circleci tests glob "./test/**/*.spec.ts" | circleci tests split)"
            yarn test ${TEST_FILES}

workflows:
  run-ci:
    jobs:
      - checkout_and_compile
      - lint:
          requires:
            - checkout_and_compile
      - test:
          requires:
            - checkout_and_compile
