version: 2.1

orbs:
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@3.0.0

jobs:
  lint:
    docker:
      - image: "cimg/base:stable"
    resource_class: large
    steps:
      - checkout
      - node/install:
          install-yarn: true
          lts: true
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Lint
          command: yarn lint
  test:
    docker:
      - image: "cimg/base:stable"
    resource_class: large
    parallelism: 10
    steps:
      - checkout
      - node/install:
          install-yarn: true
          lts: true
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Hardhat Test
          command: |
            TEST_FILES="$(circleci tests glob "./test/**/*[!.common].ts" | circleci tests split)"
            yarn test:parallel ${TEST_FILES}
  lint-and-test:
    docker:
      - image: "cimg/base:stable"
    resource_class: small
    steps:
      - run:
          name: Success
          command: echo "Success"

workflows:
  run-ci:
    jobs:
      - lint
      - test
      - lint-and-test:
          requires:
            - lint
            - test
