version: 2.1

orbs:
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@3.0.0

jobs:
  checkout_and_compile:
    docker:
      - image: "cimg/base:stable"
    resource_class: large
    steps:
      - checkout
      - node/install:
          install-yarn: true
          lts: true
      - node/install-packages:
          pkg-manager: yarn
      - run: node --version
  test:
    docker:
      - image: "cimg/base:stable"
    resource_class: large
    parallelism: 5
    steps:
      - checkout
      - node/install:
          install-yarn: true
          lts: true
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Hardhat Test
          command: |
            TEST_FILES="$(circleci tests glob "./test/**/*.test.ts" | circleci tests split)"
            yarn test ${TEST_FILES}

workflows:
  run-ci:
    jobs:
      - checkout_and_compile
      - node/run:
          yarn-run: lint
      - test:
          requires:
            - checkout_and_compile
