version: 2.1

orbs:
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@3.0.0

jobs:
  checkout_and_compile:
    docker:
      - image: "cimg/base:stable"
    resource_class: large
    working_directory: ~/artblocks-contracts
    steps:
      - checkout
      - node/install:
          install-yarn: true
          lts: true
      - node/install-packages:
          pkg-manager: yarn
      - run: node --version
      - run:
          name: Compile
          command: yarn compile
      - save_cache:
          paths:
            - ~/artblocks-contracts
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
  lint:
    docker:
      - image: "cimg/base:stable"
    resource_class: large
    working_directory: ~/artblocks-contracts
    steps:
      - checkout
      - restore_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: yarn lint
  test:
    docker:
      - image: "cimg/base:stable"
    resource_class: large
    working_directory: ~/artblocks-contracts
    steps:
      - checkout
      - restore_cache:
          key: compiled-env-{{ .Environment.CIRCLE_SHA1 }}
      - run: node --version
      - run:
          name: Run tests
          command: yarn test

workflows:
  run-ci:
    jobs:
      - checkout_and_compile
      - lint:
          requires:
            - checkout_and_compile
      - test:
          requires:
            - checkout_and_compile
