name: Frontend SDK Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sdk-build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # support latest LTS and latest stable

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --frozen-lockfile
        working-directory: packages/sdk
      - name: Build
        run: yarn run build
        working-directory: packages/sdk
      - name: Typechain
        run: yarn run build:typechain
        working-directory: packages/sdk
      - name: Run Tests
        run: yarn run test
        working-directory: packages/sdk
