name: Frontend SDK Linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sdk-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # support latest LTS and latest stable

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable && yarn --frozen-lockfile
        working-directory: packages/sdk
      - name: Lint
        run: yarn run lint
        working-directory: packages/sdk
